# Generated by Django 5.0.6 on 2024-06-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_location', models.CharField(max_length=100)),
                ('event_created', models.DateTimeField(auto_now_add=True)),
                ('event_modified', models.DateTimeField(auto_now=True)),
                ('event_artists', models.ManyToManyField(to='artist.artist', verbose_name='artists for the event')),
            ],
        ),
    ]
