# Generated by Django 5.0.6 on 2024-06-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_alter_event_options_event_event_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_created']},
        ),
    ]
