# Generated by Django 5.0.6 on 2024-06-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_event_options'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.venue'),
        ),
    ]
