# Generated by Django 5.0.6 on 2024-06-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('student', 'Student')], max_length=50, verbose_name='Ticket Type'),
        ),
    ]
